[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = { version = "3", optional = true }
hifitime = "3.9.0"
tokio = { version = "1", features = ["sync"], optional = true }

[features]
tokio = ["dep:tokio"]
ctrlc = ["dep:ctrlc"]
